name: testapi

on: 
    push:
        branches:
            - "main"

jobs:
    build:
        name: Docker image
        runs-on: ubuntu-latest 
        steps:
            - # checkout to the build machine
                name: Checkout
                uses: actions/checkout@v3
            - # login to Docker Hub 
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                  username: ${{secrets.DOCKERHUB_USERNAME }}
                  password: ${{secrets.DOCKERHUB_TOKEN }}

            - # create a build kit builder instance
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
                
            - # build the image and push it to Docker Hub
                name: Build and push
                uses: docker/build-push-action@v4
                with:
                  context: ./testapi
                  file: ./testapi/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/testapi:${{github.sha}}
            
            -   name: Azure Kubernetes set context
                uses: Azure/aks-set-context@v1
                with:
                  # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
                  creds: '${{secrets.AZURE_CREDENTIALS}}'
                  # Resource Group Name
                  resource-group: TEST-RG
                  # AKS Cluster Name
                  cluster-name: newlook
            
            # Create K8s secrets to pull images
            -   name: Create secret in Kubernetes cluster
                uses: Azure/k8s-create-secret@v1.1
                with:
                  # Container registry url
                  container-registry-url: https://hub.docker.com/repository/docker/e880613/testapi/
                  # Container registry username
                  container-registry-username: '${{secrets.DOCKERHUB_USERNAME}}'
                  # Container registry password
                  container-registry-password:  '${{secrets.DOCKERHUB_TOKEN}}'
                  # Type of Kubernetes secret. For example, docker-registry or generic
                  secret-type: docker-registry
                  # Name of the secret. You can use this secret name in the Kubernetes YAML configuration file.
                  secret-name: docker-image-pull-secret
                    
                  # Deploy to k8s cluster
            -   name: Deploy to Kubernetes cluster
                uses: Azure/k8s-deploy@v1
                with:        
                  # Path to the manifest files which will be used for deployment.
                  manifests: |
                    k8s/deployment.yml
                    k8s/service.yml
                  # Fully qualified resource URL of the image(s) to be used for substitutions on the manifest files Example: contosodemo.azurecr.io/helloworld:test
                  images: '${{secrets.DOCKERHUB_USERNAME}}/testapi:${{github.sha}}'
                  # Name of a docker-registry secret that has already been set up within the cluster. Each of these secret names are added under imagePullSecrets field for the workloads found in the input manifest files
                  imagepullsecrets: docker-image-pull-secret
                  # deploy/promote/reject
                  action: deploy