name: testapi

on: 
    push:
        branches:
            - "main"

jobs:
    build:
        name: Docker image
        runs-on: ubuntu-latest 
        steps:
            - # checkout to the build machine
                name: Checkout
                uses: actions/checkout@v3
            - # login to Docker Hub 
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                  username: ${{secrets.DOCKERHUB_USERNAME }}
                  password: ${{secrets.DOCKERHUB_TOKEN }}

            - name: docker build
              run: docker build -t githubactions-aks-demo:'${{github.sha}}' .
                
            - name: docker login
              run: docker login --username '${{secrets.DOCKERHUB_USERNAME}}' --password '${{secrets.DOCKERHUB_TOKEN}}'
                  
            - name: tag docker image
              run: docker tag githubactions-aks-demo:'${{github.sha}}' '${{secrets.DOCKERHUB_USERNAME}}'/githubactions-aks-demo:'${{github.sha}}'
                
            - name: push docker image
              run: docker push '${{secrets.DOCKERHUB_USERNAME}}'/githubactions-aks-demo:'${{github.sha}}'

            # - # create a build kit builder instance
            #     name: Set up Docker Buildx
            #     uses: docker/setup-buildx-action@v2
            # - # build the image and push it to Docker Hub
            #     name: Build and push
            #     uses: docker/build-push-action@v4
            #     with:
            #       context: ./testapi
            #       file: ./testapi/Dockerfile
            #       push: true
            #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/testapi:latest
